CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE TABLE "Accounts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Order" integer NOT NULL,
        "Name" character varying(120) NOT NULL,
        "Type" integer NOT NULL,
        "IsArchived" boolean NOT NULL,
        "ArchivedAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE TABLE "Categories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Color" character varying(32) NOT NULL,
        "EnvelopeLimit" numeric(18,2),
        "SupportsLineItems" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE TABLE "Logs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Message" text NOT NULL,
        "MessageTemplate" text NOT NULL,
        "Level" text NOT NULL,
        "Timestamp" timestamp with time zone NOT NULL,
        "Exception" text,
        "Properties" text,
        CONSTRAINT "PK_Logs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE TABLE "MonthPlans" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Year" integer NOT NULL,
        "Month" integer NOT NULL,
        "IsClosed" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_MonthPlans" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE TABLE "AccountMonthBalances" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AccountId" integer NOT NULL,
        "Year" integer NOT NULL,
        "Month" integer NOT NULL,
        "ClosingBalance" numeric NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AccountMonthBalances" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AccountMonthBalances_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE TABLE "RegularIncomeDefinitions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(160) NOT NULL,
        "Amount" numeric NOT NULL,
        "DayOfMonth" integer NOT NULL,
        "AccountId" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_RegularIncomeDefinitions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RegularIncomeDefinitions_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE TABLE "Tags" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "CategoryId" integer NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Tags" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Tags_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE TABLE "MonthSavingsTransferItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MonthPlanId" integer NOT NULL,
        "Amount" numeric NOT NULL,
        "TransferDate" date NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_MonthSavingsTransferItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MonthSavingsTransferItems_MonthPlans_MonthPlanId" FOREIGN KEY ("MonthPlanId") REFERENCES "MonthPlans" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE TABLE "Incomes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Year" integer NOT NULL,
        "Month" integer NOT NULL,
        "Name" character varying(160) NOT NULL,
        "Amount" numeric NOT NULL,
        "ExpectedDayOfMonth" date NOT NULL,
        "AccountId" integer NOT NULL,
        "IsRegular" boolean NOT NULL,
        "RegularIncomeDefinitionId" integer,
        "IsDeleted" boolean NOT NULL,
        "DeletedAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Incomes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Incomes_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Incomes_RegularIncomeDefinitions_RegularIncomeDefinitionId" FOREIGN KEY ("RegularIncomeDefinitionId") REFERENCES "RegularIncomeDefinitions" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE TABLE "RegularExpenseDefinitions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Order" integer NOT NULL,
        "Name" character varying(160) NOT NULL,
        "CategoryId" integer NOT NULL,
        "TagId" integer,
        "Amount" numeric NOT NULL,
        "IsActive" boolean NOT NULL,
        "ShowRemainingInUI" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_RegularExpenseDefinitions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RegularExpenseDefinitions_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_RegularExpenseDefinitions_Tags_TagId" FOREIGN KEY ("TagId") REFERENCES "Tags" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE TABLE "Expenses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MonthPlanId" integer NOT NULL,
        "Order" integer NOT NULL,
        "Name" character varying(200) NOT NULL,
        "CategoryId" integer NOT NULL,
        "TagId" integer,
        "RegularExpenseDefinitionId" integer,
        "PlannedAmount" numeric NOT NULL,
        "ActualAmount" numeric NOT NULL,
        "ShowRemainingInUI" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Expenses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Expenses_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Expenses_MonthPlans_MonthPlanId" FOREIGN KEY ("MonthPlanId") REFERENCES "MonthPlans" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Expenses_RegularExpenseDefinitions_RegularExpenseDefinition~" FOREIGN KEY ("RegularExpenseDefinitionId") REFERENCES "RegularExpenseDefinitions" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Expenses_Tags_TagId" FOREIGN KEY ("TagId") REFERENCES "Tags" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE TABLE "ExpenseLineItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ExpenseId" integer NOT NULL,
        "Description" character varying(300) NOT NULL,
        "Amount" numeric NOT NULL,
        "OccurredAt" date NOT NULL,
        "TagId" integer,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ExpenseLineItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ExpenseLineItems_Expenses_ExpenseId" FOREIGN KEY ("ExpenseId") REFERENCES "Expenses" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ExpenseLineItems_Tags_TagId" FOREIGN KEY ("TagId") REFERENCES "Tags" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE UNIQUE INDEX "IX_AccountMonthBalances_AccountId_Year_Month" ON "AccountMonthBalances" ("AccountId", "Year", "Month");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE INDEX "IX_Accounts_Order" ON "Accounts" ("Order");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE INDEX "IX_ExpenseLineItems_ExpenseId" ON "ExpenseLineItems" ("ExpenseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE INDEX "IX_ExpenseLineItems_TagId" ON "ExpenseLineItems" ("TagId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE INDEX "IX_Expenses_CategoryId" ON "Expenses" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE INDEX "IX_Expenses_MonthPlanId_Order" ON "Expenses" ("MonthPlanId", "Order");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE UNIQUE INDEX "IX_Expenses_MonthPlanId_RegularExpenseDefinitionId" ON "Expenses" ("MonthPlanId", "RegularExpenseDefinitionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE INDEX "IX_Expenses_RegularExpenseDefinitionId" ON "Expenses" ("RegularExpenseDefinitionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE INDEX "IX_Expenses_TagId" ON "Expenses" ("TagId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE INDEX "IX_Incomes_AccountId" ON "Incomes" ("AccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE INDEX "IX_Incomes_RegularIncomeDefinitionId" ON "Incomes" ("RegularIncomeDefinitionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE INDEX "IX_Incomes_Year_Month" ON "Incomes" ("Year", "Month");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE UNIQUE INDEX "IX_Incomes_Year_Month_RegularIncomeDefinitionId" ON "Incomes" ("Year", "Month", "RegularIncomeDefinitionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE UNIQUE INDEX "IX_MonthPlans_Year_Month" ON "MonthPlans" ("Year", "Month");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE INDEX "IX_MonthSavingsTransferItems_MonthPlanId" ON "MonthSavingsTransferItems" ("MonthPlanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE INDEX "IX_MonthSavingsTransferItems_TransferDate" ON "MonthSavingsTransferItems" ("TransferDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE INDEX "IX_RegularExpenseDefinitions_CategoryId" ON "RegularExpenseDefinitions" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE INDEX "IX_RegularExpenseDefinitions_IsActive" ON "RegularExpenseDefinitions" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE INDEX "IX_RegularExpenseDefinitions_Order" ON "RegularExpenseDefinitions" ("Order");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE INDEX "IX_RegularExpenseDefinitions_TagId" ON "RegularExpenseDefinitions" ("TagId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE INDEX "IX_RegularIncomeDefinitions_AccountId" ON "RegularIncomeDefinitions" ("AccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE INDEX "IX_RegularIncomeDefinitions_IsActive" ON "RegularIncomeDefinitions" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    CREATE INDEX "IX_Tags_CategoryId" ON "Tags" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407061343_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260407061343_Initial', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407100549_AddTagLineItemsOverrideAndRegularIncomeOptions') THEN
    ALTER TABLE "Tags" ADD "SupportsLineItemsOverride" boolean;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407100549_AddTagLineItemsOverrideAndRegularIncomeOptions') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260407100549_AddTagLineItemsOverrideAndRegularIncomeOptions', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407144514_AddTagHierarchyParent') THEN
    DROP INDEX "IX_Tags_CategoryId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407144514_AddTagHierarchyParent') THEN
    ALTER TABLE "Tags" ADD "ParentTagId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407144514_AddTagHierarchyParent') THEN
    CREATE INDEX "IX_Tags_CategoryId_ParentTagId" ON "Tags" ("CategoryId", "ParentTagId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407144514_AddTagHierarchyParent') THEN
    CREATE INDEX "IX_Tags_ParentTagId" ON "Tags" ("ParentTagId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407144514_AddTagHierarchyParent') THEN
    ALTER TABLE "Tags" ADD CONSTRAINT "FK_Tags_Tags_ParentTagId" FOREIGN KEY ("ParentTagId") REFERENCES "Tags" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407144514_AddTagHierarchyParent') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260407144514_AddTagHierarchyParent', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410191230_LoansManagement') THEN
    ALTER TABLE "Expenses" ADD "LoanInstallmentId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410191230_LoansManagement') THEN
    CREATE TABLE "Loans" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(160) NOT NULL,
        "LoanType" integer NOT NULL,
        "InterestMode" integer NOT NULL,
        "WiborPeriodType" integer,
        "Principal" numeric NOT NULL,
        "InterestRate" numeric NOT NULL,
        "MarginRate" numeric,
        "RepaymentDayOfMonth" integer NOT NULL,
        "StartDate" date NOT NULL,
        "EndDate" date NOT NULL,
        "TagId" integer,
        "IsActive" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Loans" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Loans_Tags_TagId" FOREIGN KEY ("TagId") REFERENCES "Tags" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410191230_LoansManagement') THEN
    CREATE TABLE "LoanCharges" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer NOT NULL,
        "Name" character varying(160) NOT NULL,
        "ChargeType" integer NOT NULL,
        "FrequencyType" integer NOT NULL,
        "Amount" numeric NOT NULL,
        "StartDate" date NOT NULL,
        "EndDate" date,
        "IsActive" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_LoanCharges" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LoanCharges_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410191230_LoansManagement') THEN
    CREATE TABLE "LoanInstallments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer NOT NULL,
        "Year" integer NOT NULL,
        "Month" integer NOT NULL,
        "DueDate" date NOT NULL,
        "Amount" numeric NOT NULL,
        "PrincipalAmount" numeric NOT NULL,
        "InterestAmount" numeric NOT NULL,
        "IsPaid" boolean NOT NULL,
        "PaidAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_LoanInstallments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LoanInstallments_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410191230_LoansManagement') THEN
    CREATE TABLE "LoanRateEntries" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer NOT NULL,
        "EffectiveFrom" date NOT NULL,
        "ReferenceRate" numeric NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_LoanRateEntries" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LoanRateEntries_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410191230_LoansManagement') THEN
    CREATE UNIQUE INDEX "IX_Expenses_LoanInstallmentId" ON "Expenses" ("LoanInstallmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410191230_LoansManagement') THEN
    CREATE INDEX "IX_LoanCharges_IsActive" ON "LoanCharges" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410191230_LoansManagement') THEN
    CREATE INDEX "IX_LoanCharges_LoanId" ON "LoanCharges" ("LoanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410191230_LoansManagement') THEN
    CREATE UNIQUE INDEX "IX_LoanInstallments_LoanId_Year_Month" ON "LoanInstallments" ("LoanId", "Year", "Month");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410191230_LoansManagement') THEN
    CREATE INDEX "IX_LoanInstallments_Year_Month" ON "LoanInstallments" ("Year", "Month");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410191230_LoansManagement') THEN
    CREATE UNIQUE INDEX "IX_LoanRateEntries_LoanId_EffectiveFrom" ON "LoanRateEntries" ("LoanId", "EffectiveFrom");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410191230_LoansManagement') THEN
    CREATE INDEX "IX_Loans_IsActive" ON "Loans" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410191230_LoansManagement') THEN
    CREATE INDEX "IX_Loans_LoanType" ON "Loans" ("LoanType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410191230_LoansManagement') THEN
    CREATE INDEX "IX_Loans_TagId" ON "Loans" ("TagId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410191230_LoansManagement') THEN
    ALTER TABLE "Expenses" ADD CONSTRAINT "FK_Expenses_LoanInstallments_LoanInstallmentId" FOREIGN KEY ("LoanInstallmentId") REFERENCES "LoanInstallments" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410191230_LoansManagement') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260410191230_LoansManagement', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    DROP INDEX "IX_MonthPlans_Year_Month";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    ALTER TABLE "RegularIncomeDefinitions" ADD "UserId" character varying(128) NOT NULL DEFAULT 'default-user';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    ALTER TABLE "RegularExpenseDefinitions" ADD "UserId" character varying(128) NOT NULL DEFAULT 'default-user';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    ALTER TABLE "MonthSavingsTransferItems" ADD "UserId" character varying(128) NOT NULL DEFAULT 'default-user';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    ALTER TABLE "MonthPlans" ADD "UserId" character varying(128) NOT NULL DEFAULT 'default-user';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    ALTER TABLE "Incomes" ADD "UserId" character varying(128) NOT NULL DEFAULT 'default-user';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    ALTER TABLE "Expenses" ADD "UserId" character varying(128) NOT NULL DEFAULT 'default-user';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    ALTER TABLE "ExpenseLineItems" ADD "UserId" character varying(128) NOT NULL DEFAULT 'default-user';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    ALTER TABLE "Accounts" ADD "UserId" character varying(128) NOT NULL DEFAULT 'default-user';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    ALTER TABLE "AccountMonthBalances" ADD "UserId" character varying(128) NOT NULL DEFAULT 'default-user';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    CREATE TABLE "Users" (
        "Id" character varying(128) NOT NULL,
        "Username" character varying(100) NOT NULL,
        "PasswordHash" character varying(256) NOT NULL,
        "HouseholdMode" integer NOT NULL,
        "BudgetOwnerUserId" character varying(128) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Users_Users_BudgetOwnerUserId" FOREIGN KEY ("BudgetOwnerUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    INSERT INTO "Users" ("Id", "Username", "PasswordHash", "HouseholdMode", "BudgetOwnerUserId", "CreatedAtUtc", "UpdatedAtUtc")
    VALUES ('default-user', 'default', '', 1, 'default-user', TIMESTAMPTZ '2026-05-16T00:00:00Z', TIMESTAMPTZ '2026-05-16T00:00:00Z');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    CREATE INDEX "IX_RegularIncomeDefinitions_UserId" ON "RegularIncomeDefinitions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    CREATE INDEX "IX_RegularExpenseDefinitions_UserId" ON "RegularExpenseDefinitions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    CREATE INDEX "IX_MonthSavingsTransferItems_UserId" ON "MonthSavingsTransferItems" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    CREATE INDEX "IX_MonthPlans_UserId" ON "MonthPlans" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    CREATE UNIQUE INDEX "IX_MonthPlans_UserId_Year_Month" ON "MonthPlans" ("UserId", "Year", "Month");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    CREATE INDEX "IX_Incomes_UserId" ON "Incomes" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    CREATE INDEX "IX_Expenses_UserId" ON "Expenses" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    CREATE INDEX "IX_ExpenseLineItems_UserId" ON "ExpenseLineItems" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    CREATE INDEX "IX_Accounts_UserId" ON "Accounts" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    CREATE INDEX "IX_AccountMonthBalances_UserId" ON "AccountMonthBalances" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    CREATE INDEX "IX_Users_BudgetOwnerUserId" ON "Users" ("BudgetOwnerUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    ALTER TABLE "AccountMonthBalances" ADD CONSTRAINT "FK_AccountMonthBalances_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    ALTER TABLE "Accounts" ADD CONSTRAINT "FK_Accounts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    ALTER TABLE "ExpenseLineItems" ADD CONSTRAINT "FK_ExpenseLineItems_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    ALTER TABLE "Expenses" ADD CONSTRAINT "FK_Expenses_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    ALTER TABLE "Incomes" ADD CONSTRAINT "FK_Incomes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    ALTER TABLE "MonthPlans" ADD CONSTRAINT "FK_MonthPlans_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    ALTER TABLE "MonthSavingsTransferItems" ADD CONSTRAINT "FK_MonthSavingsTransferItems_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    ALTER TABLE "RegularExpenseDefinitions" ADD CONSTRAINT "FK_RegularExpenseDefinitions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    ALTER TABLE "RegularIncomeDefinitions" ADD CONSTRAINT "FK_RegularIncomeDefinitions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516100803_UserScoping') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260516100803_UserScoping', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516143143_AddUserAdminRole') THEN
    ALTER TABLE "Users" ADD "IsAdmin" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516143143_AddUserAdminRole') THEN
    UPDATE "Users" SET "IsAdmin" = TRUE
    WHERE "Id" = 'default-user';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516143143_AddUserAdminRole') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260516143143_AddUserAdminRole', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516173448_AddUserIdToLoans') THEN
    ALTER TABLE "Loans" ADD "UserId" character varying(128) NOT NULL DEFAULT 'default-user';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516173448_AddUserIdToLoans') THEN
    CREATE INDEX "IX_Loans_UserId" ON "Loans" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516173448_AddUserIdToLoans') THEN
    ALTER TABLE "Loans" ADD CONSTRAINT "FK_Loans_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516173448_AddUserIdToLoans') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260516173448_AddUserIdToLoans', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522154545_AddAuditLogs') THEN
    CREATE TABLE "AuditLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EntityType" character varying(80) NOT NULL,
        "EntityId" integer NOT NULL,
        "UserId" character varying(128) NOT NULL,
        "BudgetOwnerUserId" character varying(128) NOT NULL,
        "Operation" character varying(32) NOT NULL,
        "OldValuesJson" jsonb NOT NULL,
        "NewValuesJson" jsonb NOT NULL,
        "ChangedAtUtc" timestamp with time zone NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AuditLogs_Users_BudgetOwnerUserId" FOREIGN KEY ("BudgetOwnerUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_AuditLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522154545_AddAuditLogs') THEN
    CREATE INDEX "IX_AuditLogs_BudgetOwnerUserId" ON "AuditLogs" ("BudgetOwnerUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522154545_AddAuditLogs') THEN
    CREATE INDEX "IX_AuditLogs_ChangedAtUtc" ON "AuditLogs" ("ChangedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522154545_AddAuditLogs') THEN
    CREATE INDEX "IX_AuditLogs_EntityType" ON "AuditLogs" ("EntityType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522154545_AddAuditLogs') THEN
    CREATE INDEX "IX_AuditLogs_Operation" ON "AuditLogs" ("Operation");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522154545_AddAuditLogs') THEN
    CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522154545_AddAuditLogs') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260522154545_AddAuditLogs', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531065511_AddLoanPercentageChargeAndOriginalInfo') THEN
    ALTER TABLE "Loans" ADD "GracePeriodMonths" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531065511_AddLoanPercentageChargeAndOriginalInfo') THEN
    ALTER TABLE "Loans" ADD "OriginalPrincipal" numeric;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531065511_AddLoanPercentageChargeAndOriginalInfo') THEN
    ALTER TABLE "LoanCharges" ADD "IsPercentageBased" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531065511_AddLoanPercentageChargeAndOriginalInfo') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260531065511_AddLoanPercentageChargeAndOriginalInfo', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601090000_AddAccountActiveFrom') THEN
    ALTER TABLE "Accounts" ADD "ActiveFromUtc" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601090000_AddAccountActiveFrom') THEN
    UPDATE "Accounts" AS account
    SET "ActiveFromUtc" = restore."ChangedAtUtc"
    FROM (
        SELECT "EntityId", MAX("ChangedAtUtc") AS "ChangedAtUtc"
        FROM "AuditLogs"
        WHERE "EntityType" = 'Account'
          AND "Operation" = 'Update'
          AND COALESCE("OldValuesJson" ->> 'IsArchived', "OldValuesJson" ->> 'isArchived') = 'true'
          AND COALESCE("NewValuesJson" ->> 'IsArchived', "NewValuesJson" ->> 'isArchived') = 'false'
        GROUP BY "EntityId"
    ) AS restore
    WHERE account."Id" = restore."EntityId"
      AND account."IsArchived" = false
      AND account."ActiveFromUtc" IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601090000_AddAccountActiveFrom') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260601090000_AddAccountActiveFrom', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603171218_AddAnnualPlans') THEN
    CREATE TABLE "AnnualPlans" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Year" integer NOT NULL,
        "ExpectedIncomeAmount" numeric(18,2) NOT NULL,
        "ExpectedSavingsAmount" numeric(18,2) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        "UserId" character varying(128) NOT NULL,
        CONSTRAINT "PK_AnnualPlans" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AnnualPlans_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603171218_AddAnnualPlans') THEN
    CREATE INDEX "IX_AnnualPlans_UserId" ON "AnnualPlans" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603171218_AddAnnualPlans') THEN
    CREATE UNIQUE INDEX "IX_AnnualPlans_UserId_Year" ON "AnnualPlans" ("UserId", "Year");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603171218_AddAnnualPlans') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260603171218_AddAnnualPlans', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260623055248_AddLoanPrepayments') THEN
    CREATE TABLE "LoanPrepayments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer NOT NULL,
        "PrepaymentDate" date NOT NULL,
        "Amount" numeric NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_LoanPrepayments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LoanPrepayments_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260623055248_AddLoanPrepayments') THEN
    CREATE INDEX "IX_LoanPrepayments_LoanId_PrepaymentDate" ON "LoanPrepayments" ("LoanId", "PrepaymentDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260623055248_AddLoanPrepayments') THEN
    INSERT INTO "LoanPrepayments" ("LoanId", "PrepaymentDate", "Amount", "CreatedAtUtc", "UpdatedAtUtc")
    SELECT
        matched."LoanId",
        make_date(matched."Year", matched."Month", 1),
        matched."ActualAmount",
        NOW(),
        NOW()
    FROM (
        SELECT
            e."Id" AS "ExpenseId",
            MAX(l."Id") AS "LoanId",
            mp."Year",
            mp."Month",
            e."ActualAmount",
            COUNT(*) AS "MatchCount"
        FROM "Expenses" e
        INNER JOIN "MonthPlans" mp
            ON mp."Id" = e."MonthPlanId"
            AND mp."UserId" = e."UserId"
        INNER JOIN "Categories" c
            ON c."Id" = e."CategoryId"
            AND c."Name" = 'Kredyt'
        INNER JOIN "Loans" l
            ON l."UserId" = e."UserId"
            AND l."Name" = left(e."Name", length(e."Name") - length(' - nadpłata'))
            AND (
                (l."TagId" IS NULL AND e."TagId" IS NULL)
                OR l."TagId" = e."TagId"
            )
        WHERE e."LoanInstallmentId" IS NULL
            AND e."RegularExpenseDefinitionId" IS NULL
            AND e."ActualAmount" > 0
            AND e."PlannedAmount" = 0
            AND e."ShowRemainingInUI" = TRUE
            AND e."Name" LIKE '% - nadpłata'
            AND e."IsDeleted" = FALSE
        GROUP BY e."Id", mp."Year", mp."Month", e."ActualAmount"
    ) matched
    WHERE matched."MatchCount" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260623055248_AddLoanPrepayments') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260623055248_AddLoanPrepayments', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702063302_AddLoanOperationAudits') THEN
    CREATE TABLE "LoanOperationAudits" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer NOT NULL,
        "UserId" character varying(128) NOT NULL,
        "BudgetOwnerUserId" character varying(128) NOT NULL,
        "OperationType" character varying(64) NOT NULL,
        "Status" character varying(32) NOT NULL,
        "OccurredAtUtc" timestamp with time zone NOT NULL,
        "ScheduleVersionBefore" character varying(128) NOT NULL,
        "ScheduleVersionAfter" character varying(128) NOT NULL,
        "OperationPayloadJson" jsonb NOT NULL,
        "RevertedAtUtc" timestamp with time zone,
        "RevertedByUserId" character varying(128),
        "RevertsOperationId" integer,
        "RevertedByOperationId" integer,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_LoanOperationAudits" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LoanOperationAudits_LoanOperationAudits_RevertedByOperation~" FOREIGN KEY ("RevertedByOperationId") REFERENCES "LoanOperationAudits" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_LoanOperationAudits_LoanOperationAudits_RevertsOperationId" FOREIGN KEY ("RevertsOperationId") REFERENCES "LoanOperationAudits" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_LoanOperationAudits_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_LoanOperationAudits_Users_BudgetOwnerUserId" FOREIGN KEY ("BudgetOwnerUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_LoanOperationAudits_Users_RevertedByUserId" FOREIGN KEY ("RevertedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_LoanOperationAudits_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702063302_AddLoanOperationAudits') THEN
    CREATE INDEX "IX_LoanOperationAudits_BudgetOwnerUserId" ON "LoanOperationAudits" ("BudgetOwnerUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702063302_AddLoanOperationAudits') THEN
    CREATE INDEX "IX_LoanOperationAudits_LoanId" ON "LoanOperationAudits" ("LoanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702063302_AddLoanOperationAudits') THEN
    CREATE INDEX "IX_LoanOperationAudits_OccurredAtUtc" ON "LoanOperationAudits" ("OccurredAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702063302_AddLoanOperationAudits') THEN
    CREATE INDEX "IX_LoanOperationAudits_OperationType" ON "LoanOperationAudits" ("OperationType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702063302_AddLoanOperationAudits') THEN
    CREATE INDEX "IX_LoanOperationAudits_RevertedByOperationId" ON "LoanOperationAudits" ("RevertedByOperationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702063302_AddLoanOperationAudits') THEN
    CREATE INDEX "IX_LoanOperationAudits_RevertedByUserId" ON "LoanOperationAudits" ("RevertedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702063302_AddLoanOperationAudits') THEN
    CREATE INDEX "IX_LoanOperationAudits_RevertsOperationId" ON "LoanOperationAudits" ("RevertsOperationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702063302_AddLoanOperationAudits') THEN
    CREATE INDEX "IX_LoanOperationAudits_Status" ON "LoanOperationAudits" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702063302_AddLoanOperationAudits') THEN
    CREATE INDEX "IX_LoanOperationAudits_UserId" ON "LoanOperationAudits" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702063302_AddLoanOperationAudits') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260702063302_AddLoanOperationAudits', '10.0.7');
    END IF;
END $EF$;
COMMIT;

