<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.7" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\HouseholdBudgetMate.Domain\HouseholdBudgetMate.Domain.csproj" />
    </ItemGroup>

</Project>
